name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 20
      - name: Set git user name
        run: git config --global user.name "mattia-consiglio"
      - name: Set git user email
        run: git config --global user.email "mattiaconsiglio96@gmail.com"
      - run: npm ci
      - run: npm run deploy
